# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ff150cec990693019510c30b1c2b48f5"
name = "NYC AgeCheck Popup"
handle = "drkellyann-checkout-18yo-modal"
application_url = "https://dolphin-app-pzgya.ondigitalocean.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-54058795.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dolphin-app-pzgya.ondigitalocean.app/auth/callback",
  "https://dolphin-app-pzgya.ondigitalocean.app/auth/shopify/callback",
  "https://dolphin-app-pzgya.ondigitalocean.app/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
